#ifndef LSL_ST_SCREENSAVER_H
#pragma once
#define LSL_ST_SCREENSAVER_H

// Interface
#define OS_SCREENSAVER_INTERFACE				"ISCREENSAVER"

// functions for setting and disabling screensaver
// these functions are not threadsave
// the time should be a value between 1 and INT_MAX
// enabled should have the value 0 or 1
//
// for setTime, getTime, getEnabled and setTime returnvalue in case of success is 0
// in case of a bad parameter it is -EINVAL or if the function fails internally -EOPNOTSUPP
#define OS_SCREENSAVER_INVALID_PARA     -22
#define OS_SCREENSAVER_INTERNAL_ERROR   -95

TYPE
	LSL_SCREENSAVER_TYPE : STRUCT
		version	: UDINT;
	//following functions are part of nVersion >= 1

	// setTimeout should set the time in seconds after witch the screensaver activates
	// set screensaver should if enabled catch all events comming from touch,mouse or keyboard, including events generated by vnc-connections
	// setting the timeout will not change the enabled state
		setTimeout : pVoid;
		getTimeout : pVoid;

	// setEnabled enables (enabled = 1) or disables (enabled =0) the screensaver mechanism
	// it does not effect the set timeout
		setEnabled : pVoid;
		getEnabled : pVoid;
	END_STRUCT;
END_TYPE

////////////////////////////////////////////////////////////////////////////////
// LASAL Function Prototypes
////////////////////////////////////////////////////////////////////////////////
FUNCTION __CDECL GLOBAL P_SCVR_setTimeout
	VAR_INPUT
		dtime	: DINT;
	END_VAR
	VAR_OUTPUT
		retval	: DINT;
	END_VAR;

FUNCTION __CDECL GLOBAL P_SCVR_getTimeout
	VAR_INPUT
		dtime	: ^DINT;
	END_VAR
	VAR_OUTPUT
		retval	: DINT;
	END_VAR;

FUNCTION __CDECL GLOBAL P_SCVR_setEnabled
	VAR_INPUT
		enabled	: DINT;
	END_VAR
	VAR_OUTPUT
		retval	: DINT;
	END_VAR;

FUNCTION __CDECL GLOBAL P_SCVR_getEnabled
	VAR_INPUT
		enabled	: ^DINT;
	END_VAR
	VAR_OUTPUT
		retval	: DINT;
	END_VAR;
  
////////////////////////////////////////////////////////////////////////////////
// LASAL MACROS
////////////////////////////////////////////////////////////////////////////////
#define OS_SCREENSAVER_SETTIMEOUT(pINTERFACE,p1) pINTERFACE^.setTimeout $ P_SCVR_setTimeout(p1)
#define OS_SCREENSAVER_GETTIMEOUT(pINTERFACE,p1) pINTERFACE^.getTimeout $ P_SCVR_getTimeout(p1)
#define OS_SCREENSAVER_SETENABLED(pINTERFACE,p1) pINTERFACE^.setEnabled $ P_SCVR_setEnabled(p1)
#define OS_SCREENSAVER_GETENABLED(pINTERFACE,p1) pINTERFACE^.getEnabled $ P_SCVR_getEnabled(p1)

#endif
