//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh__Config__PTofCls__LMCPublisher 
  {
    CHMETH *pMeth;
    _Config_ dData;
    SVRDSC *pDsc;
  } SvrCh__Config__PTofCls__LMCPublisher;

typedef struct CltCh__Config__PTofCls__LMCPublisher 
  {
    struct SvrCh__Config__PTofCls__LMCPublisher *pCh;
    _Config_ dData;
    SVRCHCMD *pCmd;
  } CltCh__Config__PTofCls__LMCPublisher;

typedef struct SvrCh__POSFLAGS 
  {
    CHMETH *pMeth;
    _POSFLAGS dData;
    SVRDSC *pDsc;
  } SvrCh__POSFLAGS;

typedef struct CltCh__POSFLAGS 
  {
    struct SvrCh__POSFLAGS *pCh;
    _POSFLAGS dData;
    SVRCHCMD *pCmd;
  } CltCh__POSFLAGS;

typedef struct SvrCh_BDINT 
  {
    CHMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrCh_BDINT;

typedef struct CltCh_BDINT 
  {
    struct SvrCh_BDINT *pCh;
    BDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_BDINT;

typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_FeSetup 
  {
    CHMETH *pMeth;
    FeSetup dData;
    SVRDSC *pDsc;
  } SvrCh_FeSetup;

typedef struct CltCh_FeSetup 
  {
    struct SvrCh_FeSetup *pCh;
    FeSetup dData;
    SVRCHCMD *pCmd;
  } CltCh_FeSetup;

typedef struct SvrCh_IO_State 
  {
    CHMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrCh_IO_State;

typedef struct CltCh_IO_State 
  {
    struct SvrCh_IO_State *pCh;
    IO_State dData;
    SVRCHCMD *pCmd;
  } CltCh_IO_State;

typedef struct SvrCh_t_e_OPMode 
  {
    CHMETH *pMeth;
    t_e_OPMode dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_OPMode;

typedef struct CltCh_t_e_OPMode 
  {
    struct SvrCh_t_e_OPMode *pCh;
    t_e_OPMode dData;
    SVRCHCMD *pCmd;
  } CltCh_t_e_OPMode;

typedef struct SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster 
  {
    CHMETH *pMeth;
    t_SDCIPortMode dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster;

typedef struct CltCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster 
  {
    struct SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster *pCh;
    t_SDCIPortMode dData;
    SVRCHCMD *pCmd;
  } CltCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd_t_e_VaranErrors 
  {
    CMDMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrChCmd_t_e_VaranErrors;

typedef struct CltChCmd__BusInterfaceSdiasDriveMng 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    _BusInterfaceSdiasDriveMng *pCmd;
  } CltChCmd__BusInterfaceSdiasDriveMng;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__Can 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Can *pCmd;
  } CltChCmd__Can;

typedef struct CltChCmd__CanLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CanLib *pCmd;
  } CltChCmd__CanLib;

typedef struct CltChCmd__CheckSum 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CheckSum *pCmd;
  } CltChCmd__CheckSum;

typedef struct SvrChCmd_iprStates 
  {
    CMDMETH *pMeth;
    iprStates dData;
    SVRDSC *pDsc;
  } SvrChCmd_iprStates;

typedef struct CltChCmd__DriveAxisBase 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    _DriveAxisBase *pCmd;
  } CltChCmd__DriveAxisBase;

typedef struct CltChCmd__DriveAxisSet 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _DriveAxisSet *pCmd;
  } CltChCmd__DriveAxisSet;

typedef struct CltChCmd__DriveErrorHandling 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    _DriveErrorHandling *pCmd;
  } CltChCmd__DriveErrorHandling;

typedef struct CltChCmd__DriveMngBase 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    _DriveMngBase *pCmd;
  } CltChCmd__DriveMngBase;

typedef struct CltChCmd__FileSys 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _FileSys *pCmd;
  } CltChCmd__FileSys;

typedef struct CltChCmd__Linker 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Linker *pCmd;
  } CltChCmd__Linker;

typedef struct CltChCmd__LMCABSEncoder 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCABSEncoder *pCmd;
  } CltChCmd__LMCABSEncoder;

typedef struct SvrChCmd__LMCAXIS_OPMODE 
  {
    CMDMETH *pMeth;
    _LMCAXIS_OPMODE dData;
    SVRDSC *pDsc;
  } SvrChCmd__LMCAXIS_OPMODE;

typedef struct CltChCmd__LMCAxis 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _LMCAxis *pCmd;
  } CltChCmd__LMCAxis;

typedef struct CltChCmd__LMCAxisBase 
  {
    struct SvrChCmd__LMCAXIS_OPMODE *pCh;
    _LMCAXIS_OPMODE dData;
    _LMCAxisBase *pCmd;
  } CltChCmd__LMCAxisBase;

typedef struct CltChCmd__LMCAxisRef 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisRef *pCmd;
  } CltChCmd__LMCAxisRef;

typedef struct CltChCmd__LMCAxisVis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVis *pCmd;
  } CltChCmd__LMCAxisVis;

typedef struct CltChCmd__LMCAxisVisInt 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisInt *pCmd;
  } CltChCmd__LMCAxisVisInt;

typedef struct CltChCmd__LMCAxisVisLogHandle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisLogHandle *pCmd;
  } CltChCmd__LMCAxisVisLogHandle;

typedef struct CltChCmd__LMCAxisVisLogViewer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisLogViewer *pCmd;
  } CltChCmd__LMCAxisVisLogViewer;

typedef struct CltChCmd__LMCAxisVisPara 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVisPara *pCmd;
  } CltChCmd__LMCAxisVisPara;

typedef struct CltChCmd__LMCAxisVOVMonitoring 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCAxisVOVMonitoring *pCmd;
  } CltChCmd__LMCAxisVOVMonitoring;

typedef struct CltChCmd__LMCMath_SO3 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCMath_SO3 *pCmd;
  } CltChCmd__LMCMath_SO3;

typedef struct CltChCmd__LMCMathFunctions 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCMathFunctions *pCmd;
  } CltChCmd__LMCMathFunctions;

typedef struct CltChCmd__LMCPublisher 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCPublisher *pCmd;
  } CltChCmd__LMCPublisher;

typedef struct CltChCmd__LMCRefBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCRefBase *pCmd;
  } CltChCmd__LMCRefBase;

typedef struct CltChCmd__LMCSafety 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _LMCSafety *pCmd;
  } CltChCmd__LMCSafety;

typedef struct CltChCmd__MultiTask 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _MultiTask *pCmd;
  } CltChCmd__MultiTask;

typedef struct CltChCmd__OSKernel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OSKernel *pCmd;
  } CltChCmd__OSKernel;

typedef struct CltChCmd__QuitErrorLMCaxis 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _QuitErrorLMCaxis *pCmd;
  } CltChCmd__QuitErrorLMCaxis;

typedef struct CltChCmd__SerLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SerLib *pCmd;
  } CltChCmd__SerLib;

typedef struct CltChCmd__StdLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _StdLib *pCmd;
  } CltChCmd__StdLib;

typedef struct CltChCmd__TaskObjectControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _TaskObjectControl *pCmd;
  } CltChCmd__TaskObjectControl;

typedef struct CltChCmd__VaranDriveBase 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    _VaranDriveBase *pCmd;
  } CltChCmd__VaranDriveBase;

typedef struct CltChCmd_AlarmOPMode3Para 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    AlarmOPMode3Para *pCmd;
  } CltChCmd_AlarmOPMode3Para;

typedef struct CltChCmd_ASCII_BIN 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ASCII_BIN *pCmd;
  } CltChCmd_ASCII_BIN;

typedef struct CltChCmd_Controller 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Controller *pCmd;
  } CltChCmd_Controller;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

typedef struct CltChCmd_CriticalSection 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    CriticalSection *pCmd;
  } CltChCmd_CriticalSection;

typedef struct CltChCmd_DataManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DataManager *pCmd;
  } CltChCmd_DataManager;

typedef struct CltChCmd_DataManagerFIFO 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    DataManagerFIFO *pCmd;
  } CltChCmd_DataManagerFIFO;

typedef struct CltChCmd_DataManagerPriority 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    DataManagerPriority *pCmd;
  } CltChCmd_DataManagerPriority;

typedef struct CltChCmd_DiasMaster 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMaster *pCmd;
  } CltChCmd_DiasMaster;

typedef struct CltChCmd_DiasMasterC 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterC *pCmd;
  } CltChCmd_DiasMasterC;

typedef struct CltChCmd_DiasMasterPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterPostScan *pCmd;
  } CltChCmd_DiasMasterPostScan;

typedef struct CltChCmd_DINT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_DINT;

typedef struct CltChCmd_EEPROM 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    EEPROM *pCmd;
  } CltChCmd_EEPROM;

typedef struct CltChCmd_FileBaseCsv 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    FileBaseCsv *pCmd;
  } CltChCmd_FileBaseCsv;

typedef struct CltChCmd_GetTaskHandle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetTaskHandle *pCmd;
  } CltChCmd_GetTaskHandle;

typedef struct CltChCmd_Hub_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base *pCmd;
  } CltChCmd_Hub_Base;

typedef struct CltChCmd_Hub_Base_Root 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base_Root *pCmd;
  } CltChCmd_Hub_Base_Root;

typedef struct CltChCmd_HwcLogging 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwcLogging *pCmd;
  } CltChCmd_HwcLogging;

typedef struct CltChCmd_HwControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControl *pCmd;
  } CltChCmd_HwControl;

typedef struct CltChCmd_HwControlBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControlBase *pCmd;
  } CltChCmd_HwControlBase;

typedef struct CltChCmd_HWKVarSizeFIFO 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HWKVarSizeFIFO *pCmd;
  } CltChCmd_HWKVarSizeFIFO;

typedef struct CltChCmd_HWRtPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HWRtPostScan *pCmd;
  } CltChCmd_HWRtPostScan;

typedef struct CltChCmd_I2CCDIAS 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    I2CCDIAS *pCmd;
  } CltChCmd_I2CCDIAS;

typedef struct CltChCmd_MerkerEx 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    MerkerEx *pCmd;
  } CltChCmd_MerkerEx;

typedef struct SvrChCmd_ProfileCommandStatus 
  {
    CMDMETH *pMeth;
    ProfileCommandStatus dData;
    SVRDSC *pDsc;
  } SvrChCmd_ProfileCommandStatus;

typedef struct CltChCmd_ProfileCommandStatus 
  {
    struct SvrChCmd_ProfileCommandStatus *pCh;
    ProfileCommandStatus dData;
    SVRCHCMD *pCmd;
  } CltChCmd_ProfileCommandStatus;

typedef struct CltChCmd_Ram 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Ram *pCmd;
  } CltChCmd_Ram;

typedef struct CltChCmd_RAMex 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RAMex *pCmd;
  } CltChCmd_RAMex;

typedef struct CltChCmd_RamFile 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RamFile *pCmd;
  } CltChCmd_RamFile;

typedef struct CltChCmd_RamRingBuffer 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RamRingBuffer *pCmd;
  } CltChCmd_RamRingBuffer;

typedef struct CltChCmd_SafetyManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SafetyManager *pCmd;
  } CltChCmd_SafetyManager;

typedef struct CltChCmd_SDCIDevice 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SDCIDevice *pCmd;
  } CltChCmd_SDCIDevice;

typedef struct CltChCmd_SDCIDevice_AsyncPara 
  {
    struct SvrChCmd_iprStates *pCh;
    iprStates dData;
    SDCIDevice_AsyncPara *pCmd;
  } CltChCmd_SDCIDevice_AsyncPara;

typedef struct CltChCmd_SDCIPort 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SDCIPort *pCmd;
  } CltChCmd_SDCIPort;

typedef struct CltChCmd_SdiasHubBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SdiasHubBase *pCmd;
  } CltChCmd_SdiasHubBase;

typedef struct CltChCmd_SdiasManager 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SdiasManager *pCmd;
  } CltChCmd_SdiasManager;

typedef struct CltChCmd_SigCLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SigCLib *pCmd;
  } CltChCmd_SigCLib;

typedef struct CltChCmd_String 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    String *pCmd;
  } CltChCmd_String;

typedef struct CltChCmd_StringInternal 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringInternal *pCmd;
  } CltChCmd_StringInternal;

typedef struct CltChCmd_StringRAM 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringRAM *pCmd;
  } CltChCmd_StringRAM;

typedef struct SvrChCmd_IO_State 
  {
    CMDMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrChCmd_IO_State;

typedef struct CltChCmd_SyncCall 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    SyncCall *pCmd;
  } CltChCmd_SyncCall;

typedef struct CltChCmd_System 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    System *pCmd;
  } CltChCmd_System;

typedef struct CltChCmd_t_e_VaranErrors 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SVRCHCMD *pCmd;
  } CltChCmd_t_e_VaranErrors;

typedef struct CltChCmd_TCPCommunication 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TCPCommunication *pCmd;
  } CltChCmd_TCPCommunication;

typedef struct CltChCmd_TCPCommunicationLogFilter 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    TCPCommunicationLogFilter *pCmd;
  } CltChCmd_TCPCommunicationLogFilter;

typedef struct CltChCmd_Varan_Base 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Varan_Base *pCmd;
  } CltChCmd_Varan_Base;

typedef struct CltChCmd_VaranManager_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    VaranManager_Base *pCmd;
  } CltChCmd_VaranManager_Base;

typedef struct CltChCmd_WatchdogDias 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    WatchdogDias *pCmd;
  } CltChCmd_WatchdogDias;

typedef struct SvrCh__CommandList_PTofCls__LMCAxisBase 
  {
    CHMETH *pMeth;
    _CommandList dData;
    SVRDSC *pDsc;
  } SvrCh__CommandList_PTofCls__LMCAxisBase;

typedef struct SvrCh__DRIVETYPE 
  {
    CHMETH *pMeth;
    _DRIVETYPE dData;
    SVRDSC *pDsc;
  } SvrCh__DRIVETYPE;

typedef struct SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _FSM_UDP_ERROR dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP;

typedef struct SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _FSM_UDP_USER dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP;

typedef struct SvrCh__I_HC_Type 
  {
    CHMETH *pMeth;
    _I_HC_Type dData;
    SVRDSC *pDsc;
  } SvrCh__I_HC_Type;

typedef struct SvrCh__INITSTEPS_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _INITSTEPS dData;
    SVRDSC *pDsc;
  } SvrCh__INITSTEPS_PTofCls_SafetyUDP;

typedef struct SvrCh__LMCAXIS_CMDERROR 
  {
    CHMETH *pMeth;
    _LMCAXIS_CMDERROR dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_CMDERROR;

typedef struct SvrCh__LMCAXIS_ERROR 
  {
    CHMETH *pMeth;
    _LMCAXIS_ERROR dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_ERROR;

typedef struct SvrCh__LMCAXIS_ERROR_CONFIG 
  {
    CHMETH *pMeth;
    _LMCAXIS_ERROR_CONFIG dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_ERROR_CONFIG;

typedef struct SvrCh__LMCAXIS_MOVE_RELATIVE_MODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVE_RELATIVE_MODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVE_RELATIVE_MODE;

typedef struct SvrCh__LMCAXIS_MOVEDIRECTION 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVEDIRECTION dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVEDIRECTION;

typedef struct SvrCh__LMCAXIS_MOVEPROFILE 
  {
    CHMETH *pMeth;
    _LMCAXIS_MOVEPROFILE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_MOVEPROFILE;

typedef struct SvrCh__LMCAXIS_POSMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_POSMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_POSMODE;

typedef struct SvrCh__LMCAXIS_POWER_OFF_MODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_POWER_OFF_MODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_POWER_OFF_MODE;

typedef struct SvrCh__LMCAXIS_REFMODE 
  {
    CHMETH *pMeth;
    _LMCAXIS_REFMODE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_REFMODE;

typedef struct SvrCh__LMCAXIS_SETPARAMETER 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETPARAMETER dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETPARAMETER;

typedef struct SvrCh__LMCAXIS_SETPOSITION 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETPOSITION dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETPOSITION;

typedef struct SvrCh__LMCAXIS_SETSWENDPOS 
  {
    CHMETH *pMeth;
    _LMCAXIS_SETSWENDPOS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_SETSWENDPOS;

typedef struct SvrCh__LMCAXIS_STATUS 
  {
    CHMETH *pMeth;
    _LMCAXIS_STATUS dData;
    SVRDSC *pDsc;
  } SvrCh__LMCAXIS_STATUS;

typedef struct SvrCh__LMCCONTROLLERTYPE 
  {
    CHMETH *pMeth;
    _LMCCONTROLLERTYPE dData;
    SVRDSC *pDsc;
  } SvrCh__LMCCONTROLLERTYPE;

typedef struct SvrCh__SDDAXISSTATE 
  {
    CHMETH *pMeth;
    _SDDAXISSTATE dData;
    SVRDSC *pDsc;
  } SvrCh__SDDAXISSTATE;

typedef struct SvrCh__SDDIDERROR 
  {
    CHMETH *pMeth;
    _SDDIDERROR dData;
    SVRDSC *pDsc;
  } SvrCh__SDDIDERROR;

typedef struct SvrCh__SDDISTATE 
  {
    CHMETH *pMeth;
    _SDDISTATE dData;
    SVRDSC *pDsc;
  } SvrCh__SDDISTATE;

typedef struct SvrCh__SDDUSERCMD 
  {
    CHMETH *pMeth;
    _SDDUSERCMD dData;
    SVRDSC *pDsc;
  } SvrCh__SDDUSERCMD;

typedef struct SvrCh_DM_CPU_Types 
  {
    CHMETH *pMeth;
    DM_CPU_Types dData;
    SVRDSC *pDsc;
  } SvrCh_DM_CPU_Types;

typedef struct SvrCh_DS402_Control 
  {
    CHMETH *pMeth;
    DS402_Control dData;
    SVRDSC *pDsc;
  } SvrCh_DS402_Control;

typedef struct SvrCh_DS402_State 
  {
    CHMETH *pMeth;
    DS402_State dData;
    SVRDSC *pDsc;
  } SvrCh_DS402_State;

typedef struct SvrCh_e_PLC_InfoOSType_PTofCls_PLC_Info 
  {
    CHMETH *pMeth;
    e_PLC_InfoOSType dData;
    SVRDSC *pDsc;
  } SvrCh_e_PLC_InfoOSType_PTofCls_PLC_Info;

typedef struct SvrCh_e_PLC_InfoProcessorType_PTofCls_PLC_Info 
  {
    CHMETH *pMeth;
    e_PLC_InfoProcessorType dData;
    SVRDSC *pDsc;
  } SvrCh_e_PLC_InfoProcessorType_PTofCls_PLC_Info;

typedef struct SvrCh_HDINT 
  {
    CHMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrCh_HDINT;

typedef struct SvrCh_SafetyConfigStateType 
  {
    CHMETH *pMeth;
    SafetyConfigStateType dData;
    SVRDSC *pDsc;
  } SvrCh_SafetyConfigStateType;

typedef struct SvrCh_t_e_ConnectionType_PTofCls_TCPCommunication 
  {
    CHMETH *pMeth;
    t_e_ConnectionType dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_ConnectionType_PTofCls_TCPCommunication;

typedef struct SvrCh_t_e_VaranErrors 
  {
    CHMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_VaranErrors;

typedef struct SvrCh_t_FaultFlagSvr_PTofCls_SDCIDevice 
  {
    CHMETH *pMeth;
    t_FaultFlagSvr dData;
    SVRDSC *pDsc;
  } SvrCh_t_FaultFlagSvr_PTofCls_SDCIDevice;

typedef struct SvrCh_t_s_SdiasFWStateStandard_PTofCls_SdiasBase 
  {
    CHMETH *pMeth;
    t_s_SdiasFWStateStandard dData;
    SVRDSC *pDsc;
  } SvrCh_t_s_SdiasFWStateStandard_PTofCls_SdiasBase;

typedef struct SvrCh_t_SDCIPortStateBits_PTofCls_SdiasSDCIMaster 
  {
    CHMETH *pMeth;
    t_SDCIPortStateBits dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDCIPortStateBits_PTofCls_SdiasSDCIMaster;

typedef struct SvrCh_t_SDCIRetCode_PTofCls_SdiasSDCIMaster 
  {
    CHMETH *pMeth;
    t_SDCIRetCode dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDCIRetCode_PTofCls_SdiasSDCIMaster;

typedef struct SvrCh_TIME_LSL 
  {
    CHMETH *pMeth;
    TIME_LSL dData;
    SVRDSC *pDsc;
  } SvrCh_TIME_LSL;

typedef struct SvrCh_UDT_KTS_TeachCommand_PTofCls_KTS_Read 
  {
    CHMETH *pMeth;
    UDT_KTS_TeachCommand dData;
    SVRDSC *pDsc;
  } SvrCh_UDT_KTS_TeachCommand_PTofCls_KTS_Read;

typedef struct SvrChCmd_DATE_LSL 
  {
    CMDMETH *pMeth;
    DATE_LSL dData;
    SVRDSC *pDsc;
  } SvrChCmd_DATE_LSL;

